#configuration for T-stage TNM
path_excel_sheet: './../resources/data_ignored/tn-val-results.xlsx'
column_actual: 'label_T'
column_predicted: 'class_T'
ignored_values:
  - '?'
path_output_dir: './../resources/results/results-tn-t-val-results'
title_confusion_matrix: Confusion Matrix Validation T-staging