#configuration for T-stage TNM
path_excel_sheet: './../resources/data/20200116-tnm-tn-val-merge.xlsx'
column_actual: 'label_TN'
column_predicted: 'class_TN'
ignored_values:
  - '?'
path_output_dir: './../resources/results/20200116-tnm-tn-val-merge'