version: '3'

services:
  doccano-dataset-tools-es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    environment:
      - node.name=es-ddt01
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - nlp-datau-network

  jupyter-nlp-datau:
    image: putssander/datascience-notebook-nlp-datau:latest
    container_name: jupyter-nlp-datau
    ports:
      - '8888:8888'
      - '6006:6006'
    volumes:
      - "./:/home/jovyan/work"
    networks:
      - nlp-datau-network

networks:
  nlp-datau-network:
    external: true