#configuration for T-stage TNM
path_excel_sheet: './../resources/data_ignored/tn-train-results.xlsx'
column_actual: 'label_N'
column_predicted: 'class_N'
ignored_values:
  - '?'
path_output_dir: './../resources/results/results-tn-n-train-results'
confusion_matrix:
  title: Confusion matrix training N-staging
  fig_size:
    x: 8
    y: 8
  font_size: large
  tick_label_font_size: medium