#configuration for T-stage TNM
path_excel_sheet: './../resources/data_ignored/tn-val-results.xlsx'
column_actual: 'label_T'
column_predicted: 'class_T'
ignored_values:
  - '?'
path_output_dir: './../resources/results/results-tn-t-val-simple-results'
confusion_matrix:
  title: Confusion Matrix Validation T-staging Simple
  fig_size:
    x: 8
    y: 8
  font_size: large
  tick_label_font_size: medium