#configuration for T-stage TNM
path_excel_sheet: './../resources/data_ignored/tn-val-results.xlsx'
column_actual: 'label_TN'
column_predicted: 'class_TN'
ignored_values:
  - '?'
path_output_dir: './../resources/results/results-tn-val-results'
confusion_matrix:
  title: Confusion Matrix Validation TN-staging
  fig_size:
    x: 16
    y: 16
  font_size: 20
  tick_label_font_size: large